### ISSUE TITLE
Fix NVidia and AMD drivers for display scaling

### ISSUE THREAD

**Issue by HUSKI3** [ix-os/IXOS#1]
broken by locals installed by lldm

**Comment by HUSKI3** [comment]
Assigned to Rick

**Comment by Destroyer117a** [comment]
not getting acces to the server

**Comment by HUSKI3** [comment]
fixed

**Comment by Destroyer117a** [comment]
![image](https://user-images.githubusercontent.com/65191897/89346326-e7888880-d6b9-11ea-85e9-5490a43af575.png)
this is the error that is being shown

![image](https://user-images.githubusercontent.com/65191897/89346437-16066380-d6ba-11ea-9cc4-4455f481cea1.png)
here is the bash script
the 'read -p' command is not completely shown but its there

**Comment by HUSKI3** [comment]
Will be added to the bleed version upon compilation of 14.72
